# Automatically merge Dependabot PRs (patch and minor only)

name: auto-merge

on:
  pull_request_target:
    types: [edited, opened, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Automerge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.STRATUS_GITHUB_TOKEN }}
